spring.application.name=springboot-survey-app

# MongoDB
spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://juan23as2_db_user:5RItUR59xA64Ys4P@cluster0.8mknl71.mongodb.net/?appName=Cluster0}
spring.data.mongodb.database=${MONGODB_DATABASE:pwa}

# Server
server.port=${PORT:9090}

# JWT
jwt.secret.key=${JWT_SECRET:nZh602fMAahjh9EHPfJsmm7Zxa0cKxRsC65NU/ZSdpjk/Cxjogce3qEXXAo4TKVF}
jwt.time.expiration=${JWT_EXPIRATION:86400000}

# Multipart (para subida de evidencias)
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=100MB

# Logging
logging.level.org.springframework.data.mongodb=WARN
logging.level.com.survey=DEBUG
