spring.application.name=springboot-survey-app

spring.mongodb.uri=mongodb+srv://juan23as2_db_user:5RItUR59xA64Ys4P@cluster0.8mknl71.mongodb.net/?appName=Cluster0
spring.mongodb.database=pwa

logging.level.org.springframework.boot.autoconfigure.mongo=DEBUG

server.port=9090

#JWT
jwt.secret.key = nZh602fMAahjh9EHPfJsmm7Zxa0cKxRsC65NU/ZSdpjk/Cxjogce3qEXXAo4TKVF
jwt.time.expiration = 86400000